windowrule {
  name = move-spotify
  match:class = Spotify
  workspace = 9
}

windowrule {
  name = move-discord
  match:class = vesktop
  workspace = 10
}

windowrule {
  name = no-gaps-wtv1
  match:float = false
  match:workspace = w[tv1]

  border_size = 0
  rounding = 0
}
